name: g_machines
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  badges: ^3.1.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  easy_localization: ^3.0.4
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_form_builder: ^9.2.1
  flutter_login: ^5.0.0
  font_awesome_flutter: ^10.7.0
  form_builder_validators: ^9.1.0
  get_it: ^7.6.7
  go_router: ^13.1.0
  lottie: ^3.0.0
  quickalert: ^1.0.2
  rxdart: ^0.27.7
  supabase_flutter: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/machines/
    - assets/problems/
    - assets/translations/
